bar/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('mybarapp/', include('mybarapp.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

mybarapp/urls.py
from django.urls import path
from . import views


app_name = 'mybarapp'
urlpatterns = [
    path('',views.index, name='index'),
    # path('<int:platillo_id>/', views.details, name='detail'),
    path('nosotros/', views.nosotros, name='nosotros'),
    path('mapa/', views.mapa, name='mapa'),
    path('timeline/', views.timeline, name='timeline'),
    path('grafico/', views.grafico, name='grafico'),
    path('platillos/', views.PlatilloListView.as_view(), name='platillos'),
    path('platillo/<int:pk>', views.PlatilloDetailView.as_view(), name='platillo-detail'),
    path('restaurantes/', views.RestauranteListView.as_view(), name='restaurantes'),
    path('restaurante/<int:pk>', views.RestauranteDetailView.as_view(), name='restaurante-detail'),
]

mybarapp/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

class Restaurante(models.Model):
    ruc_res_id = models.BigIntegerField(primary_key=True)
    restaurante = models.CharField(max_length=30)
    facultad = models.CharField(max_length=30)
    horario_ini = models.TimeField()
    horario_fin = models.TimeField()

    def __str__(self):
        return self.restaurante

    def get_absolute_url(self):
        return reverse('mybarapp:restaurante-detail', args=[str(self.ruc_res_id)])

    class Meta:
        ordering = ["restaurante"]

# class Usuario(models.Model):
#     nombre_real = models.CharField(max_length=30)
#     correo = models.EmailField()
#     usuario = models.CharField(max_length=30)
#     password = models.CharField(max_length=30)

class Platillo(models.Model):
    platillo = models.CharField(max_length=30)
    calorias = models.DecimalField(max_digits=8, decimal_places=2)
    grasa = models.DecimalField(max_digits=8, decimal_places=2)
    carbohidratos = models.DecimalField(max_digits=8, decimal_places=2)
    proteinas = models.DecimalField(max_digits=8, decimal_places=2)
    image = models.ImageField(upload_to='media/platillos/')

    class Meta:
        ordering = ["platillo"]

    def __str__(self):
        return self.platillo

    def get_absolute_url(self):
        return reverse('mybarapp:platillo-detail',args=[self.id])


class Precio(models.Model):

    STAR_CHOICES = (
        (0, 'Cero Estrella'),
        (1, 'Una Estrella'),
        (2, "Dos Estrellas"),
        (3, "Tres Estrellas"),
        (4, "Cuatro Estrellas"),
        (5, "Cinco Estrellas")
    )

    restaurante = models.ForeignKey(Restaurante, on_delete=models.CASCADE)
    platillo = models.ForeignKey(Platillo, on_delete=models.CASCADE)
    calificacion = models.PositiveSmallIntegerField(choices=STAR_CHOICES,default=0)
    precio = models.FloatField()
    comentario = models.TextField()


# class Typos_usuarios(models.Model):
#     usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
#     tipo = models.CharField(max_length=25)



# class Venta(models.Model):
#     precio = models.ForeignKey(Precio, on_delete=models.CASCADE)
#     hora_reserva = models.DateTimeField()

mybarapp/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required

from .models import Restaurante, Platillo, Precio
# Create your views here.

def index(request):

    lista_platillos = {}
    return render(request, 'mybarapp/index.html', lista_platillos)

def nosotros(request):
    return render(request, 'mybarapp/nosotros.html',{})

def mapa(request):
    return render(request, 'mybarapp/mapa.html', {})

def timeline(request):
    return render(request, 'mybarapp/timeline.html', {})

@login_required
def grafico(request):
    return render(request, 'mybarapp/grafico.html', {})

class PlatilloListView(LoginRequiredMixin,generic.ListView):
    model = Platillo

class PlatilloDetailView(LoginRequiredMixin, generic.DetailView):
    model = Platillo

class RestauranteListView(LoginRequiredMixin, generic.ListView):
    model = Restaurante

class RestauranteDetailView(LoginRequiredMixin,generic.DetailView):
    model = Restaurante

mybarapp/templates/bar/base_generic.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>
            {% block title %}Web | Servilleta{% endblock %}
        </title>
        <meta name="author" content="Yo mismo">
        <meta name="description" content="Conoce el menu del dia, separa tu comida, no pierdas tiempo en largas filas, informate del valor nutricional de tu comida">
            
        <!-- Required meta tags -->
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">

        <!-- google font -->
        <link href="https://fonts.googleapis.com/css?family=Gloria+Hallelujah|Handlee|Permanent+Marker|Varela+Round|Monda" rel="stylesheet">            

        <!-- my styles -->
        {% block stylesheet %}{% endblock%}

        <!-- head-scripts -->
        {% block head-script %}{% endblock %}
    </head>
    <body>
        <header>
            <nav class="navbar navbar-expand-md navbar-dark bg-dark mynavbar">
                <a href="index.html" class="navbar-brand">
                    <img src="{%static 'bar/img/logo/vegetarian-32.png'%}" alt="logo">
                    Servilleta
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'bar:index' %}">Home <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'bar:nosotros' %}">Nosotros</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'bar:mapa' %}">Mapa</a>
                        </li>
                        <li class="nav-item">
                            <!-- <a class="nav-link disabled" href="#">Disabled</a> -->
                            <a class="nav-link" href="{% url 'bar:timeline' %}">Top-2</a>
                        </li>
                        <li>
                            <a class="nav-link" href="{% url 'bar:grafico' %}">Grafico</a>
                        </li>
                    </ul>
                </div>                
            </nav>            
            {% block header %}{% endblock%}
        </header>
        
        {% block content %}
            content of my web
        {% endblock %}
        
        <footer class="container-fluid bg-dark text-light text-center">
            <p class="float-right"><a href="#">Back to top</a></p>
            <p class="pt-4">Copyright &copy; 2017 Xenial, Inc. Todos los derechos reservados &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
        </footer>        
        <!-- scripts -->
        {% block javascript %}{% endblock %}
        <!-- bootstrap -->
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
    </body>
</html>

mybarapp/templates/bar/blocks.html
{% extends 'base_generic.html' %}
{% load static %}

{% block title %}Servilleta | {% endblock %}

{% block stylesheet %}
{% endblock %}

{% block header %}
{% endblock %}

{% block content %}
{% endblock %}

{% block javascript %}
{% endblock %}

mybarapp/templates/bar/grafico.html
{% extends "bar/base_generic.html" %}
{% load static %}

{% block title %}Grafico | Servilleta{% endblock %}

{% block stylesheet %}
<link rel="stylesheet" href="{% static 'bar/styles/grafico.css' %}">
{% endblock %}


{% block content %}
<div id="votaciones" class="container">
    <h2>Votaciones</h2>
    <div class="chart"></div>  
</div>
{% endblock %}

{% block javascript %}
<script src="{% static 'bar/scripts/grafico.js' %}"></script>
<script src="http://d3js.org/d3.v3.min.js"></script>
{% endblock %}

mybarapp/templates/bar/index.html
{% extends "bar/base_generic.html" %}
{% load static %}

{% block title %}Servilleta{% endblock %}

{% block stylesheet %}
<link rel="stylesheet" href="{% static 'bar/styles/style.css' %}">
{% endblock %}

{% block header%}
<div class="jumbotron">
        <h1 class="display-3">Hola, listo para comer!</h1>
        <p class="lead">Aqui podras conocer informacion nutricional de los alimentos que se ofrecen en cada restaurante de nuestra hermosa Universidad.</p><br>
        <p class="lead">Puedes realizar busquedas por comida, por restaurant y por facultad</p>
    </div>
    <!-- <div class="col-sm-10"></div>   -->
    
<div class="col-12">
    <form>
        <div class="form-group row mx-1">
            <!-- <label for="exampleInputEmail1">Email address</label> -->
            <input type="search" class="form-control form-control-lg col-md-8" id="exampleInputEmail1" placeholder="Busque por comida, restaurant, facultad">
            <button type="submit" class="btn btn-primary col-md-4 btn-lg">Buscar</button>
        </div>    
    </form>                
</div>
{% endblock %}

{% block content %}
<section class="pb-2">
    <div class="container text-center">
        <div id="comidas" class="row pt-3">
            <div class="col-lg-3 col-md-6 border rounded border-dark">
                <h2 id="h2platillo0">&nbsp;</h2>
                <img class="rounded" src="{% static 'bar/img/servilleta/r1.jpg' %}" alt="Un exquisito platillo">
                <!-- <p id="myp">Valor nutricional: Calories: 80, Fat: 3g, Carbs: 13g, Protein: 2g</p> -->
                <p id="pnutricional0">
                    <strong>Valor nutricional:</strong>
                </p>
                <div class="row text-center mx-auto">
                    <strong>Restaurante: &nbsp;</strong>
                    <!-- <p id="pname1">Bar-fiec</p> -->
                    <p id="pname0"></p>
                </div>
                <div class="row text-center mx-auto">
                    <strong>Facultad: &nbsp;</strong>
                    <!-- <p id="pfacultad1">Fiec</p> -->
                    <p id="pfacultad0"></p>
                </div>
                <p><a href="#" class="btn btn-secondary" role="button">Detalles &raquo;</a></p>
            </div>
            <div class="col-lg-3 col-md-6 border rounded border-dark">
                <h2 id="h2platillo1">&nbsp;</h2>
                <img class="rounded" src="{% static 'bar/img/servilleta/r1.jpg' %}" alt="Un exquisito platillo">
                <p id="pnutricional1">
                    <strong>Valor nutricional:</strong>
                </p>
                <div class="row text-center mx-auto">
                    <strong>Restaurante: &nbsp;</strong>
                    <p id="pname1"></p>
                </div>
                <div class="row text-center mx-auto">
                    <strong>Facultad: &nbsp;</strong>
                    <p id="pfacultad1"></p>
                </div>
                <p><a href="#" class="btn btn-secondary" role="button">Detalles &raquo;</a></p>
            </div>
            <div class="col-lg-3 col-md-6 border rounded border-dark">
                <h2 id="h2platillo2">&nbsp;</h2>
                <img class="rounded" src="{% static 'bar/img/servilleta/r1.jpg' %}" alt="Un exquisito platillo">
                <p id="pnutricional2">
                    <strong>Valor nutricional:</strong>
                </p>
                <div class="row text-center mx-auto">
                    <strong>Restaurante: &nbsp;</strong>
                    <p id="pname2"></p>
                </div>
                <div class="row text-center mx-auto">
                    <strong>Facultad: &nbsp;</strong>
                    <p id="pfacultad2">Fiec</p>
                </div>
                <p><a href="#" class="btn btn-secondary" role="button">Detalles &raquo;</a></p>
            </div>                                
        </div>
    </div>

    <div class="container">
        <ul id="mylist" class="list-unstyled mt-5">
            <li class="media">
                <img class="mr-3 rounded" src="{% static 'bar/img/servilleta/r2.jpg' %}" alt="Generic placeholder image">
                <div class="media-body">
                <h5 id="h2platillo3" class="mt-0 mb-1">&nbsp;</h5>
                    <div id="pnutricional3" class="nutritional-info">
                        <span>Porcion:1 plato,&nbsp;</span>
                    </div>
                    <span>Restaurant:&nbsp;</span>
                    <span id="pname3">delicia</span><br>
                    <span>Facultad:&nbsp;</span>
                    <span id="pfacultad3">fiec</span>
                </div>
            </li>
            <li class="media my-4">
                <img class="mr-3 rounded" src="{% static 'bar/img/servilleta/r3.jpg' %}" alt="Generic placeholder image">
                <div class="media-body">
                <h5 id="h2platillo4" class="mt-0 mb-1">&nbsp;</h5>
                    <div id="pnutricional4" class="nutritional-info">
                        <span>Porcion:1 plato,&nbsp;</span>                                
                    </div>    
                    <span>Restaurant:&nbsp;</span>
                    <span id="pname4">delicia</span><br>
                    <span>Facultad:&nbsp;</span>
                    <span id="pfacultad4">fiec</span>
                </div>
            </li>
            <li class="media">
                <img class="mr-3 rounded" src="{% static 'bar/img/servilleta/r4.jpg' %}" alt="Generic placeholder image">
                <div class="media-body">
                <h5 id="h2platillo5" class="mt-0 mb-1">&nbsp;</h5>
                    <div id="pnutricional5" class="nutritional-info">
                        <span>Porcion:1 plato,&nbsp;</span>                                                                
                    </div>    
                    <span>Restaurant:&nbsp;</span>
                    <span id="pname5"></span><br>
                    <span>Facultad:&nbsp;</span>
                    <span id="pfacultad5"></span>                    
                </div>
            </li>
        </ul>          
    </div>
    <div id="mydiv-sug" class="container">
        <hr class="my-4">
        <p>Tienes sugerencias, preguntas, estamos encantados de recibir preguntas y comentarios, siente libre de dejarnos tus comentarios.</p>
        <p class="lead">
            <a class="btn btn-primary btn-lg" href="#" role="button">Escribir sugerencia</a>
        </p>
    </div>
</section>    
{% endblock %}

{% block javascript %}
<!--<script src="{% static 'bar/data/data.json' %}"></script>-->
<script src="{% static 'bar/scripts/myfunctions.js' %}"></script>
<script src="{% static 'bar/scripts/script.js' %}"></script>
{% endblock %}

mybarapp/templates/bar/login.html
{% extends "bar/base_generic.html" %}
{% load static %}

{% block title %}Login | Servilleta{% endblock %}

{% block stylesheet %}
<link rel="stylesheet" href="{% static 'bar/styles/style-nosotros.css' %}">
{% endblock %}

{% block header %}

<section>
    <form action="/bar/login_validation/" method="post"> {% csrf_token %}
    
        <div>
        
            <label for="name">Usuario:</label>
        
            <input type="text" id="user_name" name="user_name">   </div>
    
        <div>
        
            <label for="mail">Contraseña:</label>
        
            <input type="password" id="user_password" name="user_password">   </div>
    
        <div class="button">
        
            <button type="submit">Ingresar</button>
            </div>
    </form>                 
</section>
{% endblock %}

mybarapp/templates/bar/login_validation.html
{% extends "bar/base_generic.html" %}
{% load static %}

{% block title %}Login | Servilleta{% endblock %}

{% block stylesheet %}
<link rel="stylesheet" href="{% static 'bar/styles/style-nosotros.css' %}">
{% endblock %}

{% block content %}
<section>
    <div class="col-md-offset-2 col-md-8 text-center">
        <h2>{{login}}</h>
    </div> 
</section>
{% endblock %}

mybarapp/templates/bar/mapa.html
{% extends "bar/base_generic.html" %}
{% load static %}

{% block title %}Mapa | Servilleta{% endblock %}

{% block stylesheet %}
<link rel="stylesheet" href="{% static 'bar/styles/mapa.css' %}">
{% endblock %}

{% block content %}
<div id="titulo" class="text-center">
    <h2>Mapa</h2>
    <p>El mapa muestra todos los restarurantes de espol</p>
</div>
<div id="container-mapa" class="container">
    <iframe id="mapa" height="800" style="border:0" src="https://www.google.com/maps/embed/v1/place?key=AIzaSyCJs6nR8XnjtzpFbM3iBxJJ9AedqmI63Mc&q=Escuela+Superior+Politécnica+del+Litoral+(ESPOL)" allowfullscreen>
    </iframe>
</div>
{% endblock %}

mybarapp/templates/bar/nosotros.html
{% extends "bar/base_generic.html" %}
{% load static %}

{% block title %}Nosotros | Servilleta{% endblock %}

{% block stylesheet %}
<link rel="stylesheet" href="{% static 'bar/styles/style-nosotros.css' %}">
{% endblock %}

{% block header %}
<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner h400">
        <div class="carousel-item active">
            <img class="d-block w-100 " src="{% static 'bar/img/servilleta/r1.jpg' %}" alt="First slide">
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="{% static 'bar/img/servilleta/r2.jpg' %}" alt="Second slide">
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="{% static 'bar/img/servilleta/r3.jpg' %}" alt="Third slide">
        </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>
{% endblock %}

{% block content %}
<section>
    <div class="box p-5 m-4 rounded border border-primary">
        <h2>Xenial inc.</h2>
        <p>somos una marca reconocida muy bien a nivel nacional en el desarrollo web. contamos una exelente cartera de clientes. Cuidamos cada detalle de nuestros cliente. Ellos son siempre nuestros socios son siempre nuestros socios son siempre nuestros socios son siempre nuestros socios</p>      
    </div>
    <div class="box p-5 m-4 rounded border border-primary">
        <h2>Mision</h2>
        <p>Ofrecer un servicio que satisfaga a nuestros clientes , brindando el resultado esperado brindando el resultado esperado brindando el resultado esperado brindando el resultado esperado brindando el resultado esperado brindando el resultado esperado</p>      
    </div>                 
</section>
{% endblock %}

mybarapp/templates/bar/timeline.html
{% extends "bar/base_generic.html" %}
{% load static %}

{% block title %}Top-2 | Servilleta{% endblock %}

{% block stylesheet %}
<link rel="stylesheet" href="{% static 'bar/styles/timeline.css' %}">
{% endblock %}

{% block content %}
<section>
    <button class="mt-2 btn btn-primary" onclick="stop();">Detener el timeline(stop me)</button>
    <h2 class="text-center text-info">Estos son los 2 mejores platillos del dia de la fecha</h2>
    <div class="timeline">
        <h2 class="text-center mydate pt-3">Viernes 8 de Diciembre del 2017</h2>
        <div class="mycontainer left">
            <div class="content">
                <h2 class="text-center">Guatita</h2>
                <img class="imgsize rounded" src="{% static 'bar/img/servilleta/r4.jpg' %}" alt="guatita">
                <strong>Restaurante:&nbsp</strong>
                <p class="d-inline-block">Mi restaurant</p><br>
                <strong>Facultad:&nbsp</strong>
                <p class="d-inline-block">FIEC</p><br>                
                <strong>Puntaje:&nbsp</strong>
                <p class="d-inline-block">70%</p>                
            </div>
        </div>
        <div class="mycontainer right">
            <div class="content">
                <h2 class="text-center">Encebollado</h2>
                <img class="imgsize rounded" src="{% static 'bar/img/servilleta/r3.jpg' %}" alt="encebollado">
                <strong>Restaurante:&nbsp</strong>
                <p class="d-inline-block">Mi Otro restaurant</p><br>
                <strong>Facultad:&nbsp</strong>
                <p class="d-inline-block">FCSH</p><br> 
                <strong>Puntaje:&nbsp</strong>
                <p class="d-inline-block">20%</p>                
            </div>
        </div>
    </div>        
</section>
{% endblock %}

{% block javascript %}
<script src="{% static 'bar/scripts/myfunctions.js' %}"></script>
<script src="{% static 'bar/scripts/timeline.js' %}"></script>
{% endblock %}

mybarapp/templates/mybarapp/base_generic.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>
            {% block title %}Web | Servilleta{% endblock %}
        </title>
        <meta name="author" content="Yo mismo">
        <meta name="description" content="Conoce el menu del dia, separa tu comida, no pierdas tiempo en largas filas, informate del valor nutricional de tu comida">
            
        <!-- Required meta tags -->
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">

        <!-- google font -->
        <link href="https://fonts.googleapis.com/css?family=Gloria+Hallelujah|Handlee|Permanent+Marker|Varela+Round|Monda" rel="stylesheet">            

        <!-- my styles -->
        <link rel="stylesheet" href="{% static 'bar/styles/general.css' %}">
        {% block stylesheet %}{% endblock%}

        <!-- head-scripts -->
        {% block head-script %}{% endblock %}
    </head>
    <body>
        <header>
            <nav class="navbar navbar-expand-md navbar-dark bg-dark mynavbar">
                <a href="{% url 'mybarapp:index' %}" class="navbar-brand">
                    <img src="{% static 'bar/img/logo/vegetarian-32.png' %}" alt="logo">
                    Servilleta
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'mybarapp:index' %}">Home <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'mybarapp:nosotros' %}">Nosotros</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'mybarapp:mapa' %}">Mapa</a>
                        </li>
                        <li class="nav-item">
                            <!-- <a class="nav-link disabled" href="#">Disabled</a> -->
                            <a class="nav-link" href="{% url 'mybarapp:timeline' %}">Top-2</a>
                        </li>
                        <li>
                            <a class="nav-link" href="{% url 'mybarapp:grafico' %}">Grafico</a>
                        </li>
                        <li>
                            <a class="nav-link" href="{% url 'mybarapp:platillos' %}">Platillos</a>
                        </li>
                        <li>
                            <a class="nav-link" href="{% url 'mybarapp:restaurantes' %}">Restaurantes</a>
                        </li>

                    </ul>
                </div>
                <ul class="nav justify-content-end">
                    {% if user.is_authenticated %}
                        <li class="nav-item text-white">
                            <div class="nav-link">Usuario: {{ user.get_username }}</div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'logout' %}?next={{ request.path }}">Logout</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link " href="{% url 'login' %}?next={{ request.path }}">Login</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>            
            {% block header %}{% endblock%}
        </header>
        
        {% block content %}
            content of my web
        {% endblock %}
        
        <footer class="container-fluid bg-dark text-light text-center">
            <p class="float-right"><a href="http://localhost:8000/admin/login/?next=/admin/">Back to top</a></p>
            <p class="pt-4">Copyright &copy; 2017 Xenial, Inc. Todos los derechos reservados &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
        </footer>        
        <!-- scripts -->
        {% block javascript %}{% endblock %}
        <!-- bootstrap -->
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
    </body>
</html>

mybarapp/templates/mybarapp/blocks.html
{% extends 'mybarapp/base_generic.html' %}
{% load static %}

{% block title %}Servilleta | {% endblock %}

{% block stylesheet %}
{% endblock %}

{% block header %}
{% endblock %}

{% block content %}
{% endblock %}

{% block javascript %}
{% endblock %}